services:
  shodan-monitor:
    image: techblog/shodan-monitor
    container_name: shodan-monitor
    restart: always
    environment:
      - NOTIFIERS= #Apprise notifiers
      - TZ=Asia/Jerusalem
      - SCHEDULE=
      - SHODAN_API_KEY=
    volumes:
      - "/etc/localtime:/etc/localtime:ro"